### ISSUE TITLE
Add more text styling options

### ISSUE THREAD

**Issue by hannesfrank** [hannesfrank/remnote-css-rem-types#2]
E.g. use this to color the back side of a card:
```css
.separator-symbol + * {
  color: blue;
}
```
